export const solutions = [
 {slug:'industrial-automation',title:'Industrial Automation',short:'Connect machine sequencing, operator interfaces and production data in one coherent control architecture.',icon:'automation',problem:'Machines often combine isolated controls, manual adjustments and limited fault visibility. Adding software without understanding the machine sequence can create more failure paths.',solution:'Define the I/O, operating modes and control sequence first. Integrate PLC logic, HMI screens, SCADA supervision and drive interfaces around explicit states, alarms and recovery procedures.',architecture:['Sensors / field I/O','PLC sequence + interlocks','VFD / servo / actuators','HMI / recipes / alarms','SCADA / data acquisition','Production monitoring'],applications:['PLC systems and machine integration','HMI and SCADA supervision','VFD speed control and servo positioning','Sensor integration and control-panel interface planning','Recipe management and production monitoring'],technologies:['PLC / HMI / SCADA','Modbus / Modbus TCP','OPC UA','PROFINET','EtherNet/IP'],value:'A defined machine state, clearer fault diagnosis and consistent operator workflows. Improvements in uptime or throughput must be measured against the existing process.',validation:['Review I/O and electrical interfaces against the actual machine.','Exercise manual, automatic, stop and fault-recovery states.','Verify network-loss behavior, watchdogs and restart conditions.'],limit:'Safety circuits, protective devices and emergency stops require application-specific engineering and validation. Supervisory software must not bypass them.'},
 {slug:'machine-vision',title:'Machine Vision',short:'Build inspection around repeatable images: optics, lighting, calibration, processing and a traceable decision.',icon:'vision',problem:'An inconsistent image cannot support a consistent inspection. Glare, motion blur, changing backgrounds and part position can overwhelm even a well-designed algorithm.',solution:'Engineer the image-acquisition conditions before choosing the inspection method. Use rules-based vision for stable features and evaluate AI when appearance variation makes fixed rules unreliable.',architecture:['Industrial camera + lighting','Trigger + image acquisition','Pre-processing + calibration','Vision / measurement','OK / NG / review decision','PLC handshake + logging'],applications:['Automated quality inspection and presence checks','Surface defect detection and object classification','OCR / code reading and label verification','Measurement and metrology with calibration','Camera-based sorting and position detection'],technologies:['OpenCV','Python','Industrial cameras','Image processing','Calibration'],value:'Repeatable inspection criteria and records that support root-cause analysis. Measurement uncertainty and error rates need validation on representative parts.',validation:['Evaluate lighting, lens, field of view and exposure at the intended line speed.','Test good, defective and borderline samples separately.','Measure repeatability and calibration stability where dimensional results matter.'],limit:'The camera, part presentation and environment determine feasibility. A clean laboratory image does not establish performance on a production line.'},
 {slug:'ai-visual-inspection',title:'AI Visual Inspection',short:'Evaluate detection, segmentation and anomaly models against the defects and uncertainty that matter to your process.',icon:'vision',problem:'Defects can vary in shape, texture or frequency. A high aggregate accuracy score may conceal missed critical defects or excessive false rejection.',solution:'Define the defect taxonomy and labeling rules. Compare a conventional baseline with classification, detection, segmentation or anomaly-detection approaches. Separate training and evaluation data by production source or batch where appropriate.',architecture:['Image acquisition','Dataset + labeling rules','Training + model evaluation','Versioned edge inference','Accept / reject / review','Image + result traceability'],applications:['Surface defect detection and segmentation','Object detection and classification','Anomaly detection for unusual appearance','AI-assisted inspection with operator review','Inspection evidence linked to a part or batch'],technologies:['PyTorch','YOLO','CNN','Anomaly detection','ONNX','OpenCV'],value:'A way to address variable visual defects and prioritize review. False accept, false reject, latency and coverage are acceptance criteria, not assumed outcomes.',validation:['Keep a held-out dataset that represents realistic variation.','Report per-defect results and test unseen conditions.','Define a review state for uncertain, missing or out-of-scope images.'],limit:'Model performance depends on data coverage and image quality. No commercial deployment, defect-detection rate or production readiness is claimed by these capability descriptions.'},
 {slug:'edge-ai',title:'Edge AI',short:'Place inference near the machine, with resource limits, model versions and predictable failure behavior.',icon:'edge',problem:'Cloud-dependent decisions can be affected by connectivity and transport latency. Small industrial devices also impose compute, memory, thermal and maintenance constraints.',solution:'Benchmark the complete acquisition-to-result path on the proposed hardware. Package models with versioned configuration, health monitoring, bounded queues and an explicit fallback for unavailable results.',architecture:['Camera / sensor input','Edge acquisition service','Pre-processing','ONNX / local inference','Result + health interface','PLC / application consumer'],applications:['Local inspection nodes','Offline-capable visual inference','Sensor-based anomaly analysis','Embedded inference and gateway processing','Model lifecycle and device-health reporting'],technologies:['ONNX Runtime','Python / C++','Linux','Edge inference','Embedded platforms'],value:'Local processing and less dependence on continuous cloud access. End-to-end latency and resource use must be established on the target hardware.',validation:['Benchmark steady-state and worst-case processing latency.','Check thermal behavior, startup, disconnects and power interruption.','Revalidate accuracy after model conversion or quantization.'],limit:'An edge AI result is advisory until a validated control interface accepts it. The control system owns motion and interlocks.'},
 {slug:'industrial-iot',title:'Industrial IoT',short:'Turn machine signals into usable records with timestamps, quality flags and a defined data contract.',icon:'data',problem:'Counters and signals are often available but inconsistent. Missing units, duplicate events or stale values make production dashboards difficult to trust.',solution:'Map the source signals and sample rates. Normalize values at a gateway, buffer interruptions and expose the freshness and quality of every value. Agree on storage and retention around the actual operational question.',architecture:['PLC / sensor / meter','Protocol adapter','Timestamp + quality validation','Edge buffer','Data store / API','Monitoring + event history'],applications:['Production counters and downtime events','Energy and process-data acquisition','Equipment-health signals','Machine-to-software integration','Remote monitoring with explicit stale-data states'],technologies:['MQTT','Modbus TCP','OPC UA','Edge gateways','Industrial networks'],value:'Better visibility into machine behavior and a consistent basis for operational review. Connectivity alone does not guarantee accurate production KPIs.',validation:['Verify units, scaling, signal quality and clock synchronization.','Test reconnection, duplicate events and store-and-forward recovery.','Confirm network segmentation and access requirements with the site.'],limit:'Protocol availability depends on the actual device and configuration. Existing machines may require additional interfaces or gateways.'},
 {slug:'industrial-software',title:'Industrial Software',short:'Create operator-facing tools, inspection records and dashboards around the way production actually works.',icon:'software',problem:'Generic software can hide exceptions that operators deal with every day. Disconnected spreadsheets and machine interfaces make it difficult to trace a decision back to its source.',solution:'Model the workflow, roles and data contract before designing screens. Build clear operator actions, audit-relevant records and integration boundaries, with explicit handling of stale data and failed requests.',architecture:['Machines / gateways / users','Validated API contracts','Application + workflow logic','Persistent records','Operator / engineering interface','Export + production review'],applications:['Manufacturing software and custom engineering tools','Industrial data dashboards','Inspection-result and image review','Recipe and job management','Quality records and report exports'],technologies:['TypeScript','Python','SQL','REST APIs','Web interfaces'],value:'Less repeated data entry and clearer traceability between an operation, its input and its result. Workflow benefits need observation with real users.',validation:['Review screens with operators and engineering stakeholders.','Test permission boundaries, failed writes and duplicate requests.','Verify export accuracy and backup/restore procedures.'],limit:'A dashboard is a supervisory interface. It must not imply that an offline signal is live or replace a validated machine control.'},
 {slug:'embedded-systems',title:'Embedded Systems',short:'Integrate sensing, firmware and communication within practical electrical and timing constraints.',icon:'edge',problem:'Embedded integration spans voltage levels, power quality, sensor behavior and firmware timing. A working bench prototype may fail under noise, reboot or prolonged operation.',solution:'Specify the electrical interfaces and timing budget. Structure firmware around defined states, watchdogs and fault reporting. Separate sensing and communications from actuator enable conditions.',architecture:['Sensors + electrical interface','MCU / firmware state machine','Signal conditioning + sampling','Communication interface','Supervisory controller','Diagnostics + configuration'],applications:['Sensor nodes and data-acquisition devices','Machine-interface modules','Embedded gateways','Custom controller prototypes','Edge-connected instrumentation'],technologies:['C / C++','MCU platforms','UART / SPI / I²C','Modbus','Embedded Linux'],value:'Application-specific sensing and interfaces with defined behavior. Hardware suitability, environmental tolerance and lifetime depend on validation.',validation:['Check power, signal levels and protection requirements.','Exercise reboot, timeout and watchdog recovery.','Evaluate noise sensitivity and extended-operation behavior.'],limit:'Prototype firmware and hardware require additional environmental, electrical and compliance assessment before production use.'},
 {slug:'robotics-integration',title:'Robotics Integration',short:'Coordinate vision, robot programs and machine sequencing through explicit handshakes and cell states.',icon:'robotics',problem:'A robot, camera and PLC may each behave correctly in isolation while failing as a coordinated cell. Ambiguous ownership of a task or recovery state creates integration risk.',solution:'Define coordinate frames, task identifiers and the PLC–robot handshake. Connect validated vision results to robot programs with bounded timing, completion sensing and recovery rules.',architecture:['Part presentation + sensing','Vision / coordinate transform','Task + job validation','PLC–robot handshake','Robot controller execution','Completion + traceability'],applications:['Vision-guided pick and place concepts','Sorting and material-handling cells','Robot-to-machine sequence integration','Coordinate calibration and part-location transfer','Cell-state monitoring and job traceability'],technologies:['Robot controllers','PLC integration','Machine vision','Industrial networks','Coordinate transforms'],value:'A clear division of responsibilities across the cell and more diagnosable integration. Cycle time and positioning results require cell-level testing.',validation:['Verify coordinate frames, calibration and working-envelope constraints.','Test timeouts, repeated commands and incomplete operations.','Validate guarding and safety with the complete cell design.'],limit:'Robot motion and safety remain with the appropriate controllers and protective systems. AI software must not directly bypass those controls.'}
];
export const industries=[
 ['manufacturing','Manufacturing','Machine integration, process visibility and repeatable inspection for discrete production.','Machine sequencing, production counters, downtime event capture and in-process inspection.','industrial-automation'],
 ['electronics','Electronics','Visual checks for components, assemblies and identifying marks.','Component presence, orientation, connector verification, OCR and defect-review workflows.','ai-visual-inspection'],
 ['food-beverage','Food & Beverage','Inspection and data interfaces designed around hygiene, product variation and line conditions.','Packaging integrity, label checks, date/code reading and process-data acquisition.','machine-vision'],
 ['logistics','Logistics','Connect identification, routing decisions and movement records.','Code reading, object classification, conveyor interfaces and event traceability.','industrial-iot'],
 ['packaging','Packaging','Inspect product presentation and synchronize decisions with the packaging process.','Label alignment, print verification, fill/presence checks and camera-based rejection.','machine-vision'],
 ['automotive-components','Automotive Components','Define inspection criteria and retain evidence for component quality checks.','Surface inspection, dimensional checks, part identification and batch-linked inspection records.','ai-visual-inspection'],
 ['warehousing','Warehousing','Make item identification and handling interfaces easier to observe and maintain.','Sorting concepts, embedded sensing, equipment monitoring and handling-event records.','robotics-integration'],
 ['quality-control','Quality Control','Build a traceable path from an inspection criterion to its result.','Inspection stations, calibrated measurement, review queues and quality-data dashboards.','industrial-software']
];
export const projects=[
 {slug:'visual-quality-inspection',title:'AI Visual Quality Inspection System',type:'Concept system',image:'inspection.svg',desc:'A reference inspection station that connects controlled image acquisition, defect analysis and traceable quality decisions.',challenge:'How can a station distinguish accepted, rejected and uncertain parts while preserving the evidence behind each result?',scope:['Triggered industrial camera and controlled illumination','Rules-based baseline compared with candidate AI methods','Versioned model, decision thresholds and image references','PLC handshake with missing-result and review states'],flow:['Trigger + capture','Pre-process','Vision / AI evaluation','OK / NG / review','PLC acknowledgement','Persist result + evidence'],validation:['Create a representative sample set with agreed defect labels.','Measure false accept, false reject and end-to-end timing.','Exercise camera loss, processing timeout and borderline samples.'],limits:'This is a design concept, not a commissioned factory installation. No trained model, performance benchmark, customer or deployment outcome is presented.'},
 {slug:'vision-sorting',title:'Machine Vision Sorting System',type:'Engineering concept',image:'inspection.svg',desc:'A camera-guided sorting architecture with job tracking, controller handshakes and confirmation sensing.',challenge:'How can a classification result be linked to the right physical object when transport timing and actuator delays vary?',scope:['Part detection and image-trigger alignment','Classification or code-reading stage','Job ID and position tracking across the transport path','Controller-owned actuation with completion sensing'],flow:['Detect part','Capture + identify','Assign job / position','Validate controller state','Route part','Confirm + record'],validation:['Test spaced, closely packed and missing parts.','Verify position association through stop/restart sequences.','Test duplicate results, late results and failed actuations.'],limits:'The diagram describes a proposed integration approach. Conveyor mechanics, accuracy, line speed and physical deployment remain unverified.'},
 {slug:'edge-inspection-node',title:'Edge AI Inspection Node',type:'Reference architecture',image:'edge.svg',desc:'A local inference node that reports an inspection result together with device health and model identity.',challenge:'How can inference remain observable and predictable when the network, camera or compute process is interrupted?',scope:['Local acquisition and bounded processing queue','Versioned ONNX model and configuration','Watchdog, health status and controller interface','Local event buffering and deliberate fallback states'],flow:['Image input','Validate frame','Local inference','Check result deadline','Result + health handshake','Buffered event log'],validation:['Benchmark on the selected device under thermal load.','Interrupt camera, network and inference services.','Check behavior after reboot and model-version changes.'],limits:'This reference architecture does not demonstrate selected hardware, a packaged model or measured real-time performance.'},
 {slug:'production-data-dashboard',title:'Industrial Data Dashboard',type:'Interface concept',image:'dashboard.svg',desc:'A supervisory interface for PLC-based production monitoring, signal quality and event history.',challenge:'How can an interface make machine data useful without hiding gaps, stale values or inconsistent timestamps?',scope:['Read-only production counters and machine-state signals','Timestamp and quality information shown with each source','Inspection and event-history views','Traceable exports with explicit data boundaries'],flow:['PLC / equipment signals','Gateway + timestamps','Validate units / quality','Persist records','Dashboard + event review','Export for analysis'],validation:['Compare displayed counters with source values.','Test disconnects, duplicates and clock drift.','Check that exports match the underlying event records.'],limits:'The visual is an interface mockup with illustrative trend data. It has no factory connection and makes no claim about live production or customer results.'}
];
export const articles=[
 {slug:'inspection-starts-with-the-image',title:'Reliable inspection starts with the image',category:'Machine vision',desc:'Why lighting, optics, triggering and calibration belong in the acceptance plan before model selection.',sections:[
 ['Start with the feature you need to see','Write down the defect or dimension that changes the decision. A surface scratch, a missing connector and an unreadable label need different acquisition conditions. Select the field of view and lens around that feature rather than around a convenient camera.'],
 ['Control variation at acquisition','Treat lighting geometry, part presentation, exposure and the trigger as a single system. Capture samples at the intended motion conditions. Document glare, shadow and position changes that make the feature ambiguous.'],
 ['Calibration is part of measurement','OpenCV describes intrinsic calibration and lens-distortion correction. These are relevant when mapping image geometry to dimensional results. Record the calibration setup and check stability; the complete measurement method still needs application-specific validation.'],
 ['Agree on an evidence set','Collect accepted, defective and borderline parts. Keep evaluation samples separate from tuning samples, and include the operational conditions the station will face. Define a hold or manual-review state for images that cannot support a dependable decision.']
 ],source:['OpenCV camera calibration documentation','https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html']},
 {slug:'vision-plc-handshake',title:'Designing the vision-to-PLC handshake',category:'Systems integration',desc:'A decision becomes useful only when the controller can associate it with the correct part and operating state.',sections:[
 ['Identify the transaction','Associate each trigger and result with a job or part identifier. Agree which component owns that identifier and how it survives a timeout or restart. A result should never silently apply to the next object on the conveyor.'],
 ['Define the contract','Specify result states, permitted transitions, deadlines and acknowledgement. Include unavailable-image, late-result and review states. Check protocol mapping, data types and update behavior against the actual controller and network.'],
 ['Keep control ownership explicit','The PLC or appropriate motion controller validates the current machine state and decides whether a result may be acted on. AI and supervisory software provide information; they do not bypass interlocks, guarding or emergency-stop circuits.'],
 ['Test failure paths before speed','Exercise missing triggers, duplicate messages, processing crashes, controller restarts and actuator failures. Confirm the physical operation with sensing where necessary. Only then benchmark the complete trigger-to-completion path.']
 ]},
 {slug:'edge-ai-evaluation',title:'What to validate before moving AI to the edge',category:'Edge AI',desc:'A practical evaluation checklist for model behavior, device constraints and recovery on the target hardware.',sections:[
 ['Measure the whole path','Inference time is only one part of the timing budget. Include image acquisition, conversion, pre-processing, queue delay and the controller interface. Evaluate timing on the selected device with the expected image size and workload.'],
 ['Check conversion against a baseline','ONNX Runtime documents quantization approaches and accuracy considerations. Compare the converted or quantized model with the baseline on representative evaluation data. A smaller model is useful only if its decision quality remains suitable for the task.'],
 ['Exercise device constraints','Run long enough to observe memory use, queue growth and thermal behavior. Check startup, camera interruption, network loss and power recovery. Record the hardware, software and model versions with the results.'],
 ['Make unavailable results visible','Expose health, freshness and deadlines to the consuming application. Decide whether a missed result causes hold, review or another defined fallback. Keep a recovery path that operators can understand and engineering teams can diagnose.']
 ],source:['ONNX Runtime quantization documentation','https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html']}
];
